export const TRY_LOGIN = "TRY_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const TRY_REGISTER = "TRY_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const CHECK_FORGOT_PW_EMAIL = "CHECK_FORGOT_PW_EMAIL";
export const FORGOT_PW_EMAIL_EXISTS = "FORGOT_PW_EMAIL_EXISTS";
export const NO_FORGOT_PW_EMAIL = "NO_FORGOT_PW_EMAIL";

export const TRY_RESET_PASSWORD = "TRY_RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
