export const TRY_LOGIN = "TRY_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const TRY_REGISTER = "TRY_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const CHECK_FORGOT_PW_EMAIL = "CHECK_FORGOT_PW_EMAIL";
export const FORGOT_PW_EMAIL_EXISTS = "FORGOT_PW_EMAIL_EXISTS";
export const NO_FORGOT_PW_EMAIL = "NO_FORGOT_PW_EMAIL";

export const TRY_RESET_PASSWORD = "TRY_RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const SHOW_ADD_CATEGORY_FORM_MODAL = "SHOW_ADD_CATEGORY_FORM_MODAL";
export const HIDE_ADD_CATEGORY_FORM_MODAL = "HIDE_ADD_CATEGORY_FORM_MODAL";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const SHOW_EDIT_CATEGORY_FORM_MODAL = "SHOW_EDIT_CATEGORY_FORM_MODAL";
export const HIDE_EDIT_CATEGORY_FORM_MODAL = "HIDE_EDIT_CATEGORY_FORM_MODAL";
export const TRY_EDIT_CATEGORY = "TRY_EDIT_CATEGORY";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILED = "EDIT_CATEGORY_FAILED";

export const SHOW_SEARCH_BAR = "SHOW_SEARCH_BAR";
export const HIDE_SEARCH_BAR = "HIDE_SEARCH_BAR";

export const SHOW_ADD_PRODUCT_TO_CATEGORY_FORM ="SHOW_ADD_PRODUCT_TO_CATEGORY_FORM";
export const HIDE_ADD_PRODUCT_TO_CATEGORY_FORM ="HIDE_ADD_PRODUCT_TO_CATEGORY_FORM";

export const POST_ADD_PRODUCT_TO_CAT ="POST_ADD_PRODUCT_TO_CAT";
export const POST_ADD_PRODUCT_TO_CAT_SUCCESS ="POST_ADD_PRODUCT_TO_CAT_SUCCESS";
export const POST_ADD_PRODUCT_TO_CAT_FAILED ="POST_ADD_PRODUCT_TO_CAT_FAILED";

export const GET_VERIFIED_PRODUCTS ="GET_VERIFIED_PRODUCTS"
export const GET_VERIFIED_PRODUCTS_SUCCESS ="GET_VERIFIED_PRODUCTS_SUCCESS"
export const GET_VERIFIED_PRODUCTS_FAILED ="GET_VERIFIED_PRODUCTS_FAILED"

export const SHOW_VERIFIED_PROD_EDIT_FORM = "SHOW_VERIFIED_PROD_EDIT_FORM";
export const HIDE_VERIFIED_PROD_EDIT_FORM = "HIDE_VERIFIED_PROD_EDIT_FORM";

// instagram
export const SEND_EMAIL_TO_SELLER_FOR_CODE ="SEND_EMAIL_TO_SELLER_FOR_CODE";

export const GET_CODE_FROM_EMAIL ="GET_CODE_FROM_EMAIL";

export const GET_CODE_FOR_ACESS_TOKEN = "GET_CODE_FOR_ACESS_TOKEN";
export const GET_CODE_FOR_ACESS_TOKEN_SUCCESS = "GET_CODE_FOR_ACESS_TOKEN_SUCCESS";
export const GET_CODE_FOR_ACESS_TOKEN_FAILED = "GET_CODE_FOR_ACESS_TOKEN_FAILED";

export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN";
export const GET_ACCESS_TOKEN_SUCCESS = "GET_ACCESS_TOKEN_SUCCESS";
export const GET_ACCESS_TOKEN_FAILED = "GET_ACCESS_TOKEN_FAILED";

export const GET_LONG_LIVED_ACCESS_TOKEN = "GET_LONG_LIVED_ACCESS_TOKEN";
export const GET_LONG_LIVED_ACCESS_TOKEN_SUCCESS = "GET_LONG_LIVED_ACCESS_TOKEN_SUCCESS";
export const GET_LONG_LIVED_ACCESS_TOKEN_FAILED = "GET_LONG_LIVED_ACCESS_TOKEN_FAILED";

export const GET_USER_POSTS_ID_CAPTION = "GET_USER_POSTS_ID_CAPTION";
export const GET_USER_POSTS_ID_CAPTION_SUCCESS = "GET_USER_POSTS_ID_CAPTION_SUCCESS";
export const GET_USER_POSTS_ID_CAPTION_FAILED = "GET_USER_POSTS_ID_CAPTION_FAILED";

export const GET_SPECIFIC_USER_POST = "GET_SPECIFIC_USER_POST";
export const GET_SPECIFIC_USER_POST_SUCCESS = "GET_SPECIFIC_USER_POST_SUCCESS";
export const GET_SPECIFIC_USER_POST_FAILED = "GET_SPECIFIC_USER_POST_FAILED";

//become a seller
export const ADD_SELLER = "ADD_SELLER";
export const ADD_SELLER_SUCCESS = "ADD_SELLER_SUCCESS";
export const ADD_SELLER_FAILED = "ADD_SELLER_FAILED";





