export const TRY_LOGIN = "TRY_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const TRY_REGISTER = "TRY_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const CHECK_FORGOT_PW_EMAIL = "CHECK_FORGOT_PW_EMAIL";
export const FORGOT_PW_EMAIL_EXISTS = "FORGOT_PW_EMAIL_EXISTS";
export const NO_FORGOT_PW_EMAIL = "NO_FORGOT_PW_EMAIL";

export const TRY_RESET_PASSWORD = "TRY_RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const SHOW_ADD_CATEGORY_FORM_MODAL = "SHOW_ADD_CATEGORY_FORM_MODAL";
export const HIDE_ADD_CATEGORY_FORM_MODAL = "HIDE_ADD_CATEGORY_FORM_MODAL";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"; 
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED"; 

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const SHOW_EDIT_CATEGORY_FORM_MODAL = "SHOW_EDIT_CATEGORY_FORM_MODAL";
export const HIDE_EDIT_CATEGORY_FORM_MODAL = "HIDE_EDIT_CATEGORY_FORM_MODAL";
export const TRY_EDIT_CATEGORY = "TRY_EDIT_CATEGORY";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_FAILED = "EDIT_CATEGORY_FAILED";
